[global]
pid=/run/php/php8.1-fpm.pid
error_log=/_/php_fpm_81.log
log_level=alert

[p81]
user=caddy
group=caddy
listen = /run/php/s81.sock
listen.owner=caddy
listen.group=caddy
listen.mode=0666

pm=dynamic
pm.max_children=64
pm.min_spare_servers=16
pm.max_spare_servers=48
pm.max_requests=1536

chdir=/
