; configuration for php opcache module
; priority=10
zend_extension=opcache.so

opcache.enable=1

opcache.jit_buffer_size=64M

opcache.jit=1255

opcache.interned_strings_buffer=8
opcache.memory_consumption=128

opcache.file_update_protection=3
opcache.force_restart_timeout=120
opcache.jit_blacklist_root_trace=18
opcache.jit_blacklist_side_trace=9
opcache.jit_max_exit_counters=12288
opcache.jit_max_loop_unrolls=9
opcache.jit_max_root_traces=1536
opcache.jit_max_side_traces=192
opcache.jit_prof_threshold=0.004
opcache.max_accelerated_files=32531
